@startuml
left to right direction
actor "User" as U

rectangle "Colors Web Application" {
    usecase "Log In" as UC1
    usecase "Log Out" as UC2
    usecase "Add Color" as UC3
    usecase "Search Colors" as UC4
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4

note right of UC3
  Persistently saves color 
  to user account
end note
@enduml